# Generated by Django 4.2.5 on 2023-09-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroke',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Others')]),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='heart_disease',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='hypertension',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='smoking_status',
            field=models.IntegerField(choices=[(0, 'Formerly Smoked'), (1, 'Never Smoked'), (2, 'Smokes')]),
        ),
    ]
